"""Emit catalog Requirement entries from extraction output + a human curation file.

Usage:
    python emit_candidates.py <clauses.json> <curation.json> <catalog.ttl>

Contract: every extracted block index must be accounted for - seeded (hand-written
in the catalog before Gate 1), skipped (with a reason), or curated (slug + summary).
Levels derive from the strongest BCP 14 keyword in the block (MUST-family >
SHOULD-family > MAY) unless the curation entry overrides with "level". clauseText
is the full block text unless the entry overrides with "text" (trimming to the
normative sentences). Hashes follow DECISIONS.md D-0008.

The generated section of the catalog file starts at MARKER; re-running replaces
everything from the marker on, so regeneration is idempotent. Never hand-edit
generated entries - edit the curation file and regenerate.
"""
import hashlib
import json
import re
import sys
import unicodedata
from pathlib import Path

MARKER = "## ================= Mass extraction (generated) ================="
TR = "https://www.w3.org/TR/lws10-core/"
DATED = "https://www.w3.org/TR/2026/WD-lws10-core-20260622/"
MUST_KW = {"MUST", "MUST NOT", "SHALL", "SHALL NOT", "REQUIRED"}
SHOULD_KW = {"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED"}
SLUG_RE = re.compile(r"[a-z0-9][a-z0-9-]*$")


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", unicodedata.normalize("NFC", text)).strip()


def digest(text: str) -> str:
    return "sha256-" + hashlib.sha256(normalize(text).encode("utf-8")).hexdigest()


def derive_level(keywords) -> str:
    ks = set(keywords)
    if ks & MUST_KW:
        return "MUST"
    if ks & SHOULD_KW:
        return "SHOULD"
    return "MAY"


def main() -> int:
    clauses = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    curation = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
    catalog = Path(sys.argv[3])
    existing = catalog.read_text(encoding="utf-8")
    hand_written = existing.split(MARKER)[0]
    existing_slugs = set(re.findall(r"^req:([A-Za-z0-9-]+)$", hand_written, re.M))

    seeded = set(curation["seeded"])
    skip = {int(k) for k in curation.get("skip", {})}
    entries = {e["i"]: e for e in curation["entries"]}
    created = curation["created"]
    known = {b["i"] for b in clauses}

    problems = []
    slugs = set()
    for block in clauses:
        i = block["i"]
        if i in seeded or i in skip:
            continue
        e = entries.get(i)
        if e is None:
            problems.append(f"block {i} (sec={block['section']}) has no curation entry")
            continue
        slug, summary = e["slug"], e["summary"]
        if not SLUG_RE.fullmatch(slug):
            problems.append(f"bad slug: {slug}")
        if slug in slugs or slug in existing_slugs:
            problems.append(f"duplicate slug: {slug}")
        slugs.add(slug)
        if '"' in summary or "\\" in summary:
            problems.append(f"{slug}: summary unsafe for a quoted literal")
        text = e.get("text", block["text"])
        if '"""' in text or text.endswith('"') or "\\" in text:
            problems.append(f"{slug}: clause text unsafe for a triple-quoted literal")
    for i in entries:
        if i not in known:
            problems.append(f"curation entry {i} matches no extracted block")
        if i in seeded:
            problems.append(f"curation entry {i} is already seeded")
    if problems:
        print("CURATION PROBLEMS:")
        for p in problems:
            print(" -", p)
        return 1

    out = [
        MARKER,
        "## Generated by tools/extractor/emit_candidates.py from the curation file in",
        "## catalog/sources/ - edit that file and regenerate; do not hand-edit below.",
        f"## Status touchstone:Draft pending batch review. Generated {created}.",
        "",
    ]
    counts = {"MUST": 0, "SHOULD": 0, "MAY": 0}
    last_top = None
    for block in clauses:
        i = block["i"]
        if i in seeded or i in skip:
            continue
        e = entries[i]
        top = block["path"][0] if block["path"] else "unknown"
        if top != last_top:
            out += [f"## ---- {top} ----", ""]
            last_top = top
        level = e.get("level") or derive_level(block["keywords"])
        counts[level] += 1
        text = e.get("text", block["text"])
        sec = block["section"]
        out += [
            f"req:{e['slug']}",
            "    a touchstone:Requirement ;",
            f"    touchstone:level \"{level}\" ;",
            "    touchstone:specModule \"lws10-core\" ;",
            f"    touchstone:section <{TR}#{sec}> ;",
            f"    touchstone:sourceDraft <{DATED}#{sec}> ;",
            f"    touchstone:summary \"{e['summary']}\" ;",
            f"    touchstone:clauseText \"\"\"{text}\"\"\" ;",
            f"    touchstone:clauseHash \"{digest(text)}\" ;",
            "    touchstone:status touchstone:Draft ;",
            f"    dcterms:created \"{created}\"^^xsd:date .",
            "",
        ]

    catalog.write_text(hand_written.rstrip() + "\n\n" + "\n".join(out), encoding="utf-8")
    total = sum(counts.values())
    print(f"emitted {total} generated entries "
          f"(MUST {counts['MUST']}, SHOULD {counts['SHOULD']}, MAY {counts['MAY']}); "
          f"{len(seeded)} seeded, {len(skip)} skipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
